const preColors: Record<string, string> = {
  appleGreen: "#83d944",
  aqua: "#1af6d2",
  aquamarine: "#0fd7b6",
  armyGreen: "#4c5a19",
  azure: "#6ea8ff",
  babyBlue: "#bde2ff",
  beige: "#e2dba2",
  black: "#000500",
  bloodred: "#890005",
  Blue: "#4c22f8",
  blueGreen: "#006d66",
  blueGrey: "#687c8f",
  bluePurple: "#843aeb",
  blueViolet: "#7f2cd8",
  brick: "#a24030",
  brickRed: "#93271b",
  brightBlue: "#5047ff",
  brightGreen: "#00fe00",
  brightPink: "#ff00af",
  brightPurple: "#d408ff",
  brightRed: "#fc0726",
  brightYellow: "#ecfb00",
  Brown: "#613b07",
  burgundy: "#60001c",
  burntOrange: "#b75303",
  burntSienna: "#a04317",
  cerulean: "#257aa9",
  chartreuse: "#b0ec00",
  coral: "#ff685f",
  cornflowerBlue: "#8f88f2",
  cream: "#ffffca",
  crimson: "#860010",
  cyan: "#3cfbfb",
  darkBlue: "#161955",
  darkBrown: "#2c1c07",
  darkGreen: "#002700",
  darkGrey: "#3c3b3d",
  darkMagenta: "#900054",
  darkOrange: "#bb4b00",
  darkPink: "#c14467",
  darkPurple: "#330833",
  darkRed: "#720008",
  darkTeal: "#004b4c",
  darkTurquoise: "#004b4e",
  darkYellow: "#bcac00",
  deepBlue: "#1f0070",
  deepPurple: "#2e0229",
  deepRed: "#820009",
  dustyRose: "#ba7674",
  eggplant: "#48243d",
  electricBlue: "#5800fe",
  flesh: "#fdcdaa",
  forestGreen: "#004118",
  fuchsia: "#cd0095",
  gold: "#ccae00",
  goldenrod: "#dbb300",
  grassGreen: "#479e19",
  Green: "#00a121",
  greenBlue: "#007763",
  greenYellow: "#bffb00",
  grey: "#858480",
  greyBlue: "#6f8b9c",
  greyGreen: "#7b9874",
  hotPink: "#ff0078",
  hunterGreen: "#002b00",
  indigo: "#3c0067",
  kellyGreen: "#00a42a",
  khaki: "#a3a764",
  lavender: "#d3a9f2",
  leafGreen: "#53a015",
  lightBlue: "#b6e7ff",
  lightBrown: "#aa8457",
  lightGreen: "#b0ff9d",
  lightGrey: "#d8dbd4",
  lightOrange: "#fbbd59",
  lightPink: "#ffdae8",
  lightPurple: "#d183ff",
  lightRed: "#fd5757",
  lightTeal: "#9addc2",
  lightTurquoise: "#9cfedc",
  lightYellow: "#ffff8f",
  lilac: "#d5acf3",
  lime: "#aeff17",
  limeGreen: "#84fb00",
  magenta: "#b30063",
  maroon: "#610021",
  mauve: "#9f6e78",
  mediumBlue: "#3364b1",
  midnightBlue: "#07002d",
  mint: "#b5ffc2",
  mossGreen: "#688b47",
  mustard: "#c2ae02",
  mustardYellow: "#bdb300",
  navyBlue: "#051742",
  neonGreen: "#00fe00",
  neonPink: "#ff00af",
  neonPurple: "#dd33ff",
  oceanBlue: "#116185",
  ochre: "#b39100",
  offWhite: "#ffffe9",
  olive: "#687613",
  Orange: "#f77d00",
  OrangeBrown: "#ac6001",
  OrangeRed: "#f35134",
  paleBlue: "#ddf9ff",
  paleGreen: "#c5fcb4",
  palePink: "#ffdee9",
  palePurple: "#bf9bbc",
  paleYellow: "#feff98",
  pastelGreen: "#b4ffa5",
  peach: "#feba83",
  peaGreen: "#82a406",
  periwinkle: "#9d8bf4",
  pink: "#ff88c4",
  pinkPurple: "#c856a9",
  pinkRed: "#ea164d",
  plum: "#622e4a",
  puce: "#925f62",
  puke: "#8a9800",
  Purple: "#86079f",
  purpleBlue: "#8a3ef2",
  red: "#d80010",
  redBrown: "#8e3d2f",
  redOrange: "#f64d25",
  robinsEggBlue: "#baf6ff",
  rose: "#c46270",
  royalBlue: "#2c0094",
  royalPurple: "#500061",
  rust: "#9d3b13",
  sage: "#93b884",
  salmon: "#fb8573",
  sand: "#ddd078",
  seaBlue: "#166e93",
  seaFoamGreen: "#94f7b6",
  seaGreen: "#0df9a1",
  skin: "#fbd2ab",
  skyBlue: "#94c9ff",
  slate: "#53606d",
  slateBlue: "#637995",
  springGreen: "#b0ff83",
  steelBlue: "#657995",
  tan: "#ceb672",
  taupe: "#a99278",
  teal: "#0f8f82",
  terracotta: "#be6448",
  turquoise: "#00c1ab",
  violet: "#a311f0",
  white: "#fffeff",
  wine: "#610631",
  yellow: "#f4f802",
  yellowBrown: "#937900",
  yellowGreen: "#b9f52f",
  yellowOrange: "#fdb925",
};
export const colorCentersFromStoneHeer = Object.fromEntries(
  Object.entries(preColors).map(([name, hex]) => [name.toLowerCase(), hex])
);

export const webColors = [
  "INDIANRED",
  "LIGHTCORAL",
  "SALMON",
  "DARKSALMON",
  "LIGHTSALMON",
  "CRIMSON",
  "RED",
  "DARKRED",
  "PINK",
  "LIGHTPINK",
  "HOTPINK",
  "DEEPPINK",
  "MEDIUMVIOLETRED",
  "PALEVIOLETRED",
  "CORAL",
  "TOMATO",
  "ORANGERED",
  "DARKORANGE",
  "ORANGE",
  "GOLD",
  "YELLOW",
  "LIGHTYELLOW",
  "LEMONCHIFFON",
  "LIGHTGOLDENRODYELLOW",
  "PAPAYAWHIP",
  "MOCCASIN",
  "PEACHPUFF",
  "PALEGOLDENROD",
  "KHAKI",
  "DARKKHAKI",
  "LAVENDER",
  "THISTLE",
  "PLUM",
  "VIOLET",
  "ORCHID",
  "FUCHSIA",
  "MAGENTA",
  "MEDIUMORCHID",
  "MEDIUMPURPLE",
  "REBECCAPURPLE",
  "BLUEVIOLET",
  "DARKVIOLET",
  "DARKORCHID",
  "DARKMAGENTA",
  "PURPLE",
  "INDIGO",
  "SLATEBLUE",
  "DARKSLATEBLUE",
  "MEDIUMSLATEBLUE",
  "GREENYELLOW",
  "CHARTREUSE",
  "LAWNGREEN",
  "LIME",
  "LIMEGREEN",
  "PALEGREEN",
  "LIGHTGREEN",
  "MEDIUMSPRINGGREEN",
  "SPRINGGREEN",
  "MEDIUMSEAGREEN",
  "SEAGREEN",
  "FORESTGREEN",
  "GREEN",
  "DARKGREEN",
  "YELLOWGREEN",
  "OLIVEDRAB",
  "OLIVE",
  "DARKOLIVEGREEN",
  "MEDIUMAQUAMARINE",
  "DARKSEAGREEN",
  "LIGHTSEAGREEN",
  "DARKCYAN",
  "TEAL",
  "AQUA",
  "CYAN",
  "LIGHTCYAN",
  "PALETURQUOISE",
  "AQUAMARINE",
  "TURQUOISE",
  "MEDIUMTURQUOISE",
  "DARKTURQUOISE",
  "CADETBLUE",
  "STEELBLUE",
  "LIGHTSTEELBLUE",
  "POWDERBLUE",
  "LIGHTBLUE",
  "SKYBLUE",
  "LIGHTSKYBLUE",
  "DEEPSKYBLUE",
  "DODGERBLUE",
  "CORNFLOWERBLUE",
  "ROYALBLUE",
  "BLUE",
  "MEDIUMBLUE",
  "DARKBLUE",
  "NAVY",
  "MIDNIGHTBLUE",
  "CORNSILK",
  "BLANCHEDALMOND",
  "BISQUE",
  "NAVAJOWHITE",
  "WHEAT",
  "BURLYWOOD",
  "TAN",
  "ROSYBROWN",
  "SANDYBROWN",
  "GOLDENROD",
  "DARKGOLDENROD",
  "PERU",
  "CHOCOLATE",
  "SADDLEBROWN",
  "SIENNA",
  "BROWN",
  "MAROON",
  "WHITE",
  "SNOW",
  "HONEYDEW",
  "MINTCREAM",
  "AZURE",
  "ALICEBLUE",
  "GHOSTWHITE",
  "WHITESMOKE",
  "SEASHELL",
  "BEIGE",
  "OLDLACE",
  "FLORALWHITE",
  "IVORY",
  "ANTIQUEWHITE",
  "LINEN",
  "LAVENDERBLUSH",
  "MISTYROSE",
  "GAINSBORO",
  "LIGHTGRAY",
  "SILVER",
  "DARKGRAY",
  "GRAY",
  "DIMGRAY",
  "LIGHTSLATEGRAY",
  "SLATEGRAY",
  "DARKSLATEGRAY",
  "BLACK",
].map((x) => `"${x}"`.toLowerCase());
